# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: mac_host

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/target/'
    Contents: '*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'mywebapp'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'myDockerRegistry'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'myDockerRegistry'
    repository: '8484810020/azuredevops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
